---
title: mfrna
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: mfrna86@gmail.com
description: For the love of code
baseurl: 
url: https://mfrna.github.io
twitter_username: mfrna
github_username: mfrna
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
- jekyll-feed
